apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api-deployment
  namespace: hello-api-stg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-api
  template:
    metadata:
      labels:
        app: hello-api
    spec:
      containers:
        - name: hello-api
          image: andrealmar/hello-api:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 400m
              memory: 300Mi
            requests:
              cpu: 200m
              memory: 150Mi
