apiVersion: v1
kind: Service
metadata:
  name: hello-api-service
  namespace: hello-api-stg
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: hello-api
